#Configuracao do banco
spring.application.name=ifood-api
spring.datasource.url=jdbc:h2:mem:ifooddb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

#Sempre quando mata aplicacao e subir novamente e atualizado as tabelas.
#Em producao nao e uma boa pratica deixa o gerador de schema do hibernete gerar as tabelas do banco.
spring.jpa.hibernate.ddl-auto= update

#Cria automaticamente as tabelas.
spring.jpa.generate-ddl = true 

#Configuracao do pool de conexao
spring.datasource.hikari.maximum-pool-size= 10 
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.idle-timeout = 10000

