#==================================
#Configuracao do banco H2
#==================================
spring.application.name=ifood-api
spring.datasource.url=jdbc:h2:mem:ifooddb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true

#==========================================================
#Sempre quando mata aplicacao e subir novamente e atualizado as tabelas.
#==========================================================
#Em producao nao e uma boa pratica deixa o gerador de schema do hibernete gerar as tabelas do banco.
    #spring.jpa.hibernate.ddl-auto= update

#==========================================================
#Cria automaticamente as tabelas.
#==========================================================
    #spring.jpa.generate-ddl = true

#==========================================================
#Configuracao do pool de conexao
#==========================================================
    spring.datasource.hikari.maximum-pool-size= 10 
    spring.datasource.hikari.minimum-idle=10
    spring.datasource.hikari.idle-timeout = 10000

#==========================================================
#Em producao
#==========================================================
    # Em producao e preciso desabilitar a geracao automatica de tabelas . Precisa ser tudo criado com versionador.
    # Nesse projeto sera utilizado o flyway e desabilitamos a geracao e atualizacao de tabelas no banco automatico.
    # Devemos evitar sql de insert em migrations em producao.

#==========================================================
#Adiciona log do flyway:
#==========================================================
    logging.level.org.flywaydb=INFO

#==========================================================
#Criar scrips de banco de dados so cria nao executa
#==========================================================
    #spring.jpa.properties.javax.persistence.schema-generation.scripts.action = create

#==========================================================
#Localizacao do arquivo onde sera armazenado o scrip.
#==========================================================
    #spring.jpa.properties.javax.persistence.schema-generation.scripts.create-target= /home/regio/dev/scrip

#==========================================================
#Serve para dizer aonde o flyway deve executar os arquivos
#==========================================================
#Em producao nao coloque o callback de testdata, pode usar o profile e em prod nao utilizar.
    spring.flyway.locations=classpath:db/migration,classpath:db/testdata


#=========================================================================================
#Serve para gerar exception caso nao tenha alguma propriedade existente no json no objeto
#=========================================================================================
spring.jackson.deserialization.fail-on-unknown-properties=true

#=========================================================================================
#Serve para gerar exception caso a propriedade exista no objeto porem ta com o @JsonIgnore
#=========================================================================================
spring.jackson.deserialization.fail-on-ignored-properties=true

#==========================================================================================
